# Neural Networks and Deep Learning

---

## 1. Introduction to Neural Networks

### What is a Neural Network?

A neural network is a machine learning model designed to mimic how our brains learn and process information. It is made up of layers of “neurons” that learn to recognize patterns.

**Anecdote**: Imagine you're teaching a toddler to recognize cats. You show many pictures of cats, and the toddler slowly begins to learn what a cat looks like. A neural network learns in a similar way-from examples.

### Structure of a Neural Network:

* **Input Layer**: Where data enters the model (like a person's height or age).
* **Hidden Layers**: These do the actual learning by detecting patterns.
* **Output Layer**: Gives the final prediction.

**Example**:

```
Input  ---> Hidden Layer ---> Output
```

---

## 2. Neural Networks in Pipelines

We use **pipelines** to keep our machine learning workflow clean and organized.

### Example with Scikit-learn and Keras:

In [60]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
import warnings
warnings.filterwarnings('ignore')

This sets up a pipeline where data is first scaled, then passed into a neural network model.

---

## 3. Gradient Descent

### What Is Gradient Descent?

It’s the method neural networks use to learn-by gradually adjusting weights to reduce prediction errors.

**Analogy**: Think of trying to walk downhill blindfolded. You feel around with your foot, find the steepest slope, and take a small step down. That’s how Gradient Descent works.

---

## 4. The Gradient in Gradient Descent

### Formula:

$$
w = w - \alpha \frac{\partial J}{\partial w}
$$

* **w** = current weight
* **α** = learning rate (step size)
* **∂J/∂w** = gradient (slope of the loss function)

### Python Code Equivalent:

In [61]:
# Initial weight
w = 5

# Suppose gradient = 0.2 and learning_rate = 0.01
gradient = 0.2
learning_rate = 0.01

# Update the weight
w = w - learning_rate * gradient
print(w)  # Output: 4.998

4.998


---

## 5. Scalars, Vectors, Matrices, and Tensors

* **Scalar** = Single value (e.g. 7)
* **Vector** = 1D list (e.g. \[7, 2])
* **Matrix** = 2D grid (e.g. \[\[1, 2], \[3, 4]])
* **Tensor** = N-dimensional array used in deep learning

Tensors help move data through a neural network.

---

## 6. Introduction to Keras

Keras is a beginner-friendly library for building neural networks.

### Example Model:

In [62]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(10,)))
model.add(Dense(1, activation='sigmoid'))

### Explanation:

* `Sequential()` = A stack of layers
* `Dense(16)` = 16 neurons
* `activation='relu'` = Adds non-linearity
* `input_shape=(10,)` = 10 input features
* `sigmoid` = Good for binary output (0 or 1)

---

## 7. Tuning Neural Networks with Normalization

### Why Normalize?

Features like age (1-100) and income (thousands) can confuse the model if not scaled.

### Example:

In [63]:
from sklearn.preprocessing import StandardScaler

import numpy as np

# Example: create some sample data
# shape: 5 samples × 3 features
X = np.array([
    [1.0, 200.0, 0.5],
    [2.0, 300.0, 0.75],
    [3.0, 400.0, 1.0],
    [4.0, 500.0, 1.25],
    [5.0, 600.0, 1.5]
])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


---

## 8. Tuning with Evaluation

### Compile and Fit the Model

In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Create dummy binary classification data
X = np.random.rand(100, 5)  # 100 samples, 5 features
y = np.random.randint(0, 2, size=(100, 1))  # binary labels

# Split into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Define model
model = Sequential([
    Dense(10, activation='relu', input_shape=(5,)),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fit
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))


Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 140ms/step - accuracy: 0.5125 - loss: 0.7883 - val_accuracy: 0.4000 - val_loss: 0.9197
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5125 - loss: 0.7804 - val_accuracy: 0.4000 - val_loss: 0.9091
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5125 - loss: 0.7745 - val_accuracy: 0.4000 - val_loss: 0.8986
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5125 - loss: 0.7681 - val_accuracy: 0.4000 - val_loss: 0.8885
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5125 - loss: 0.7619 - val_accuracy: 0.4000 - val_loss: 0.8793
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5125 - loss: 0.7565 - val_accuracy: 0.4000 - val_loss: 0.8705
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5125 - loss: 0.7506 - val_accuracy: 0.4000 - val_loss: 0.8623
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5125 - loss: 0.7453 - val_accuracy: 0.4000 - val_loss: 0.8541

* `optimizer='adam'` = Smart way to adjust weights
* `loss='binary_crossentropy'` = Good for binary classification
* `validation_data` = See performance on new (unseen) data

---

## 9. Tuning with Regularization

### Dropout

Drops some neurons randomly during training to prevent overfitting.

In [58]:
from keras.layers import Dropout
model.add(Dropout(0.3))

### L1/L2 Regularization

Adds a penalty to large weights.

In [59]:
from keras.regularizers import l2
model.add(Dense(64, kernel_regularizer=l2(0.01)))

---

## Exercises

1. Build a simple neural network using Keras.
2. Normalize your dataset and compare model performance.
3. Try using Dropout and L2 regularization. What changes?
4. Implement a basic Gradient Descent loop in Python.
5. Use `model.evaluate()` on your test data. What metric does best?

---

## Summary

* Neural Networks are inspired by the brain and learn from data.
* Gradient Descent adjusts weights to reduce error.
* Keras simplifies model creation.
* Normalization, Evaluation, and Regularization improve model performance.
* Tensors are how data moves through the network.

---